name: Run Warhammer Battle

on:
  push:
    branches: [ '**' ]
    paths:
      - 'battlefields/*.yml'

jobs:
  setup-battle:
    if: github.ref_name != 'master'
    runs-on: ubuntu-latest
    outputs:
      battlefield_file: ${{ steps.set_vars.outputs.battlefield_file }}
      rules_file: ${{ steps.set_vars.outputs.rules_file }}
      current_player: ${{ steps.set_vars.outputs.current_player }}
      current_phase: ${{ steps.set_vars.outputs.current_phase }}
      turn_number: ${{ steps.set_vars.outputs.turn_number }}
      all_phases: ${{ steps.get_phases.outputs.all_phases }}
      initial_phase_name: ${{ steps.set_vars.outputs.current_phase }} # Output the initial phase from battlefield.yml
      battlefield_dir: ${{ steps.set_vars.outputs.battlefield_dir }}
      initial_battlefield_artifact_name: initial-battlefield-state
      temp_battlefield_file: ${{ steps.set_vars.outputs.temp_battlefield_file }} # New output for temp file
      phases_to_skip: ${{ steps.get_skip_phases.outputs.phases_to_skip }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get battlefield and rules file paths
        id: set_vars
        run: |
          BATTLEFIELD_FILE=$(find battlefields -maxdepth 1 -name "*.yml" | head -n 1)
          echo "battlefield_file=$BATTLEFIELD_FILE" >> $GITHUB_OUTPUT
          echo "rules_file=rules/whfb6.yml" >> $GITHUB_OUTPUT

          BATTLEFIELD_DIR=$(dirname "$BATTLEFIELD_FILE")
          echo "battlefield_dir=$BATTLEFIELD_DIR" >> $GITHUB_OUTPUT

          # Create temporary battlefield file path
          TEMP_BATTLEFIELD_FILE="${BATTLEFIELD_FILE%.yml}_tmp.yml"
          echo "temp_battlefield_file=$TEMP_BATTLEFIELD_FILE" >> $GITHUB_OUTPUT

          # Copy original battlefield content to temporary file for initial processing
          cp "$BATTLEFIELD_FILE" "$TEMP_BATTLEFIELD_FILE"

          CURRENT_PLAYER=$(ruby -ryaml -e "puts YAML.load_file('"$TEMP_BATTLEFIELD_FILE"')['current_turn']['player']")
          echo "current_player=$CURRENT_PLAYER" >> $GITHUB_OUTPUT

          CURRENT_PHASE=$(ruby -ryaml -e "data = YAML.load_file('$TEMP_BATTLEFIELD_FILE'); puts data['current_turn'] && data['current_turn']['phase'] ? data['current_turn']['phase'] : ''")
          echo "current_phase=$CURRENT_PHASE" >> $GITHUB_OUTPUT

          TURN_NUMBER=$(ruby -ryaml -e "puts YAML.load_file('$TEMP_BATTLEFIELD_FILE')['current_turn']['turn_number']")
          echo "turn_number=$TURN_NUMBER" >> $GITHUB_OUTPUT

      - name: Get all phases from rules file
        id: get_phases
        run: |
          ALL_PHASES=$(ruby -ryaml -rjson -e "puts YAML.load_file('${{ steps.set_vars.outputs.rules_file }}')['phases'].map { |phase| phase['name'] }.to_json")
          echo "ALL_PHASES: $ALL_PHASES"
          echo "all_phases=$(echo "$ALL_PHASES" | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Define phases to skip
        id: get_skip_phases
        run: |
          # Define which phases to skip - modify this list as needed
          SKIP_PHASES='["Movement Phase", "Magic Phase", "Shooting Phase"]'
          echo "SKIP_PHASES: $SKIP_PHASES"
          echo "phases_to_skip=$SKIP_PHASES" >> $GITHUB_OUTPUT

      - name: Upload initial temporary battlefield artifact
        uses: actions/upload-artifact@v4
        with:
          name: initial-battlefield-state # Use a consistent name for the artifact
          path: ${{ steps.set_vars.outputs.temp_battlefield_file }} # Upload the specific temporary file
          retention-days: 1 # Keep artifacts for a short period

  movement-phase:
    uses: ./.github/workflows/movement_phase.yml
    needs: setup-battle
    with:
      battlefield_artifact_name: ${{ needs.setup-battle.outputs.initial_battlefield_artifact_name }}
      temp_battlefield_file: ${{ needs.setup-battle.outputs.temp_battlefield_file }}
      battlefield_dir: ${{ needs.setup-battle.outputs.battlefield_dir }}
      current_phase_name: 'Movement Phase'
      all_phases_list: ${{ needs.setup-battle.outputs.all_phases }}
      skip_execution: ${{ contains(needs.setup-battle.outputs.phases_to_skip, 'Movement Phase') }}
    secrets: inherit
    if: success() && (needs.setup-battle.outputs.initial_phase_name == 'Movement Phase' || contains(fromJson(needs.setup-battle.outputs.all_phases), needs.setup-battle.outputs.initial_phase_name))

  magic-phase:
    uses: ./.github/workflows/magic_phase.yml
    needs: 
      - movement-phase
      - setup-battle
    with:
      battlefield_artifact_name: ${{ needs.movement-phase.outputs.next_battlefield_artifact_name }}
      temp_battlefield_file: ${{ needs.movement-phase.outputs.temp_battlefield_file }}
      battlefield_dir: ${{ needs.movement-phase.outputs.battlefield_dir }}
      current_phase_name: 'Magic Phase'
      all_phases_list: ${{ needs.movement-phase.outputs.all_phases_list }}
      skip_execution: ${{ contains(needs.setup-battle.outputs.phases_to_skip, 'Magic Phase') }}
    secrets: inherit
    if: success() && needs.movement-phase.outputs.next_phase_output == 'Magic Phase'

  shooting-phase:
    uses: ./.github/workflows/shooting_phase.yml
    needs:
      - magic-phase
      - setup-battle
    with:
      battlefield_artifact_name: ${{ needs.magic-phase.outputs.next_battlefield_artifact_name }}
      temp_battlefield_file: ${{ needs.magic-phase.outputs.temp_battlefield_file }}
      battlefield_dir: ${{ needs.magic-phase.outputs.battlefield_dir }}
      current_phase_name: 'Shooting Phase'
      all_phases_list: ${{ needs.magic-phase.outputs.all_phases_list }}
      phases_to_skip: ${{ needs.setup-battle.outputs.phases_to_skip }}
      skip_execution: ${{ contains(needs.setup-battle.outputs.phases_to_skip, 'Shooting Phase') }}
    secrets: inherit
    if: success() && needs.magic-phase.outputs.next_phase_output == 'Shooting Phase'

  combat-phase:
    uses: ./.github/workflows/combat_phase.yml
    needs:
      - shooting-phase
      - setup-battle
    with:
      battlefield_artifact_name: ${{ needs.shooting-phase.outputs.next_battlefield_artifact_name }}
      temp_battlefield_file: ${{ needs.shooting-phase.outputs.temp_battlefield_file }}
      battlefield_dir: ${{ needs.shooting-phase.outputs.battlefield_dir }}
      current_phase_name: 'Combat Phase'
      all_phases_list: ${{ needs.shooting-phase.outputs.all_phases_list }}
      skip_execution: ${{ contains(needs.setup-battle.outputs.phases_to_skip, 'Combat Phase') }}
    secrets: inherit
    if: success() && needs.shooting-phase.outputs.next_phase_output == 'Combat Phase'

  morale-phase:
    uses: ./.github/workflows/morale_phase.yml
    needs:
      - combat-phase
      - setup-battle
    with:
      battlefield_artifact_name: ${{ needs.combat-phase.outputs.next_battlefield_artifact_name }}
      temp_battlefield_file: ${{ needs.combat-phase.outputs.temp_battlefield_file }}
      battlefield_dir: ${{ needs.combat-phase.outputs.battlefield_dir }}
      current_phase_name: 'Morale Phase'
      all_phases_list: ${{ needs.combat-phase.outputs.all_phases_list }}
      skip_execution: ${{ contains(needs.setup-battle.outputs.phases_to_skip, 'Morale Phase') }}
    secrets: inherit
    if: success() && needs.combat-phase.outputs.next_phase_output == 'Morale Phase'

  finish-turn-and-commit:
    runs-on: ubuntu-latest
    needs:
      - setup-battle
      - movement-phase
      - magic-phase
      - shooting-phase
      - combat-phase
      - morale-phase
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Download final battlefield artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.morale-phase.outputs.next_battlefield_artifact_name }}
          path: ${{ needs.morale-phase.outputs.battlefield_dir }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Install dependencies (Psych)
        run: gem install psych

      - name: Update turn data and save battlefield
        run: ruby main.rb ${{ needs.morale-phase.outputs.temp_battlefield_file }} ${{ needs.setup-battle.outputs.rules_file }}

      - name: Commit changes to battlefield file
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          BATTLEFIELD_FILE="${{ needs.setup-battle.outputs.battlefield_file }}"
          TEMP_BATTLEFIELD_FILE="${{ needs.morale-phase.outputs.temp_battlefield_file }}"
          ACTUAL_TEMP_BATTLEFIELD_FILE="$TEMP_BATTLEFIELD_FILE"
          cp "$ACTUAL_TEMP_BATTLEFIELD_FILE" "$BATTLEFIELD_FILE"
          CURRENT_PLAYER=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['player']")
          TURN_NUMBER=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['turn_number']")
          git add ${{ needs.setup-battle.outputs.battlefield_file }}
          git commit -m "Automated Battle Turn: Turn ${TURN_NUMBER} - ${CURRENT_PLAYER}" || echo "No changes to commit"
          git push
