name: Run Warhammer Battle

on:
  push:
    branches: [ '**' ]
    paths:
      - 'battlefields/*.yml'

jobs:
  setup-battle:
    if: github.ref_name != 'master'
    runs-on: ubuntu-latest
    outputs:
      battlefield_file: ${{ steps.set_vars.outputs.battlefield_file }}
      rules_file: ${{ steps.set_vars.outputs.rules_file }}
      current_player: ${{ steps.set_vars.outputs.current_player }}
      current_phase: ${{ steps.set_vars.outputs.current_phase }}
      turn_number: ${{ steps.set_vars.outputs.turn_number }}
      all_phases: ${{ steps.get_phases.outputs.all_phases }}
      initial_phase_name: ${{ steps.set_vars.outputs.current_phase }} # Output the initial phase from battlefield.yml
      battlefield_dir: ${{ steps.set_vars.outputs.battlefield_dir }}
      initial_battlefield_artifact_name: initial-battlefield-state

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get battlefield and rules file paths
        id: set_vars
        run: |
          BATTLEFIELD_FILE=$(find battlefields -maxdepth 1 -name "*.yml" | head -n 1)
          echo "battlefield_file=$BATTLEFIELD_FILE" >> $GITHUB_OUTPUT
          echo "rules_file=rules/whfb6.yml" >> $GITHUB_OUTPUT

          BATTLEFIELD_DIR=$(dirname "$BATTLEFIELD_FILE")
          echo "battlefield_dir=$BATTLEFIELD_DIR" >> $GITHUB_OUTPUT

          CURRENT_PLAYER=$(ruby -ryaml -e "puts YAML.load_file('"$BATTLEFIELD_FILE"')['current_turn']['player']")
          echo "current_player=$CURRENT_PLAYER" >> $GITHUB_OUTPUT

          CURRENT_PHASE=$(ruby -ryaml -e "data = YAML.load_file('$BATTLEFIELD_FILE'); puts data['current_turn'] && data['current_turn']['phase'] ? data['current_turn']['phase'] : ''")
          echo "current_phase=$CURRENT_PHASE" >> $GITHUB_OUTPUT

          TURN_NUMBER=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['turn_number']")
          echo "turn_number=$TURN_NUMBER" >> $GITHUB_OUTPUT

      - name: Get all phases from rules file
        id: get_phases
        run: |
          ALL_PHASES=$(ruby -ryaml -rjson -e "puts YAML.load_file('${{ steps.set_vars.outputs.rules_file }}')['phases'].map { |phase| phase['name'] }.to_json")
          echo "ALL_PHASES: $ALL_PHASES"
          echo "all_phases=$(echo "$ALL_PHASES" | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Upload battlefield artifact
        uses: actions/upload-artifact@v4
        with:
          name: initial-battlefield-state # Use a consistent name for the artifact
          path: ${{ steps.set_vars.outputs.battlefield_file }}

  movement-phase:
    runs-on: ubuntu-latest
    needs: setup-battle
    if: needs.setup-battle.outputs.initial_phase_name == 'Movement Phase'
    outputs:
      next_phase_output: ${{ steps.determine_next_phase.outputs.next_phase_output }}
      next_battlefield_artifact_name: movement-phase-battlefield-state
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download battlefield artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.setup-battle.outputs.initial_battlefield_artifact_name }}
          path: .

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Run Movement Phase
        run: ruby phases/movement_phase.rb ${{ needs.setup-battle.outputs.battlefield_file }}

      - name: Determine next phase
        id: determine_next_phase
        run: |
          BATTLEFIELD_FILE="${{ needs.setup-battle.outputs.battlefield_file }}"
          NEXT_PHASE=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['phase']")
          echo "next_phase_output=$NEXT_PHASE" >> $GITHUB_OUTPUT

      - name: Upload battlefield artifact
        uses: actions/upload-artifact@v4
        with:
          name: movement-phase-battlefield-state
          path: ${{ needs.setup-battle.outputs.battlefield_file }}

  magic-phase:
    runs-on: ubuntu-latest
    needs: movement-phase
    if: needs.movement-phase.outputs.next_phase_output == 'Magic Phase'
    outputs:
      next_phase_output: ${{ steps.determine_next_phase.outputs.next_phase_output }}
      next_battlefield_artifact_name: magic-phase-battlefield-state
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download battlefield artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.movement-phase.outputs.next_battlefield_artifact_name }}
          path: .

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Run Magic Phase
        run: ruby phases/magic_phase.rb ${{ needs.setup-battle.outputs.battlefield_file }}

      - name: Determine next phase
        id: determine_next_phase
        run: |
          BATTLEFIELD_FILE="${{ needs.setup-battle.outputs.battlefield_file }}"
          NEXT_PHASE=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['phase']")
          echo "next_phase_output=$NEXT_PHASE" >> $GITHUB_OUTPUT

      - name: Upload battlefield artifact
        uses: actions/upload-artifact@v4
        with:
          name: magic-phase-battlefield-state
          path: ${{ needs.setup-battle.outputs.battlefield_file }}

  shooting-phase:
    runs-on: ubuntu-latest
    needs: magic-phase
    if: needs.magic-phase.outputs.next_phase_output == 'Shooting Phase'
    outputs:
      next_phase_output: ${{ steps.determine_next_phase.outputs.next_phase_output }}
      next_battlefield_artifact_name: shooting-phase-battlefield-state
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download battlefield artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.magic-phase.outputs.next_battlefield_artifact_name }}
          path: .

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Run Shooting Phase
        run: ruby phases/shooting_phase.rb ${{ needs.setup-battle.outputs.battlefield_file }}

      - name: Determine next phase
        id: determine_next_phase
        run: |
          BATTLEFIELD_FILE="${{ needs.setup-battle.outputs.battlefield_file }}"
          NEXT_PHASE=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['phase']")
          echo "next_phase_output=$NEXT_PHASE" >> $GITHUB_OUTPUT

      - name: Upload battlefield artifact
        uses: actions/upload-artifact@v4
        with:
          name: shooting-phase-battlefield-state
          path: ${{ needs.setup-battle.outputs.battlefield_file }}

  combat-phase:
    runs-on: ubuntu-latest
    needs: shooting-phase
    if: needs.shooting-phase.outputs.next_phase_output == 'Combat Phase'
    outputs:
      next_phase_output: ${{ steps.determine_next_phase.outputs.next_phase_output }}
      next_battlefield_artifact_name: combat-phase-battlefield-state
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download battlefield artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.shooting-phase.outputs.next_battlefield_artifact_name }}
          path: .

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Run Combat Phase
        run: ruby phases/combat_phase.rb ${{ needs.setup-battle.outputs.battlefield_file }}

      - name: Determine next phase
        id: determine_next_phase
        run: |
          BATTLEFIELD_FILE="${{ needs.setup-battle.outputs.battlefield_file }}"
          NEXT_PHASE=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['phase']")
          echo "next_phase_output=$NEXT_PHASE" >> $GITHUB_OUTPUT

      - name: Upload battlefield artifact
        uses: actions/upload-artifact@v4
        with:
          name: combat-phase-battlefield-state
          path: ${{ needs.setup-battle.outputs.battlefield_file }}

  morale-phase:
    runs-on: ubuntu-latest
    needs: combat-phase
    if: needs.combat-phase.outputs.next_phase_output == 'Morale Phase'
    outputs:
      next_phase_output: ${{ steps.determine_next_phase.outputs.next_phase_output }}
      next_battlefield_artifact_name: morale-phase-battlefield-state
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download battlefield artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.combat-phase.outputs.next_battlefield_artifact_name }}
          path: .

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Run Morale Phase
        run: ruby phases/morale_phase.rb ${{ needs.setup-battle.outputs.battlefield_file }}

      - name: Determine next phase
        id: determine_next_phase
        run: |
          BATTLEFIELD_FILE="${{ needs.setup-battle.outputs.battlefield_file }}"
          NEXT_PHASE=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['phase']")
          echo "next_phase_output=$NEXT_PHASE" >> $GITHUB_OUTPUT

      - name: Upload battlefield artifact
        uses: actions/upload-artifact@v4
        with:
          name: morale-phase-battlefield-state
          path: ${{ needs.setup-battle.outputs.battlefield_file }}

  finish-turn-and-commit:
    runs-on: ubuntu-latest
    needs: morale-phase
    if: always() # Always run to finalize the turn or commit game over state
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download final battlefield artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.morale-phase.outputs.next_battlefield_artifact_name }}
          path: .

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Install dependencies (Psych)
        run: gem install Psych

      - name: Update turn data and save battlefield
        run: ruby main.rb ${{ needs.setup-battle.outputs.battlefield_file }} ${{ needs.setup-battle.outputs.rules_file }}

      - name: Commit changes to battlefield file
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          BATTLEFIELD_FILE="${{ needs.setup-battle.outputs.battlefield_file }}"
          CURRENT_PLAYER=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['player']")
          TURN_NUMBER=$(ruby -ryaml -e "puts YAML.load_file('$BATTLEFIELD_FILE')['current_turn']['turn_number']")
          git add ${{ needs.setup-battle.outputs.battlefield_file }}
          git commit -m "Automated Battle Turn: Turn ${TURN_NUMBER} - ${CURRENT_PLAYER}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
