on:
  workflow_call:
    inputs:
      battlefield_artifact_name:
        required: true
        type: string
      temp_battlefield_file:
        required: true
        type: string
      battlefield_dir:
        required: true
        type: string
      current_phase_name:
        required: true
        type: string
      all_phases_list:
        required: true
        type: string
      skip_execution:
        required: false
        type: boolean
        default: false
    outputs:
      next_phase_output:
        value: ${{ jobs.morale_phase_job.outputs.next_phase_output }}
      next_battlefield_artifact_name:
        value: ${{ jobs.morale_phase_job.outputs.next_battlefield_artifact_name }}
      temp_battlefield_file:
        value: ${{ jobs.morale_phase_job.outputs.temp_battlefield_file }}
      battlefield_dir:
        value: ${{ jobs.morale_phase_job.outputs.battlefield_dir }}

jobs:
  morale_phase_job:
    runs-on: ubuntu-latest
    outputs:
      next_phase_output: ${{ steps.determine_next_phase.outputs.next_phase_output }}
      next_battlefield_artifact_name: morale-phase-battlefield-state
      temp_battlefield_file: ${{ inputs.temp_battlefield_file }}
      battlefield_dir: ${{ inputs.battlefield_dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download battlefield artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.battlefield_artifact_name }}
          path: ${{ inputs.battlefield_dir }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Execute Morale Phase
        if: ${{ ! inputs.skip_execution }}
        run: ruby phases/morale_phase.rb ${{ inputs.temp_battlefield_file }}

      - name: Determine next phase
        id: determine_next_phase
        run: |
          ALL_PHASES_JSON='${{ inputs.all_phases_list }}'
          CURRENT_PHASE_NAME='${{ inputs.current_phase_name }}'

          # Use jq to parse the JSON array and find the next phase
          NEXT_PHASE=$(echo "$ALL_PHASES_JSON" | jq -r '.[]' | awk -v current="$CURRENT_PHASE_NAME" '$1 == current {f=1; next} f==1 {print; f=0}' | head -n 1)

          echo "next_phase_output=$NEXT_PHASE" >> $GITHUB_OUTPUT

      - name: Upload battlefield artifact
        uses: actions/upload-artifact@v4
        with:
          name: morale-phase-battlefield-state
          path: ${{ inputs.temp_battlefield_file }}
          retention-days: 1
